[workspace]
members = [
    "larashell",
    "larashell_terminal",
    "larashell_config",
    "larashell_config_derive",
]
resolver = "2"

[profile.release]
lto = "thin"
debug = 1
incremental = false
